# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
org.gradle.parallel=true

# AndroidX libraries use the AndroidX namespace instead of the historic Support Library.
android.useAndroidX=true

# Automatically convert third-party libraries to use AndroidX AndroidX.
android.enableJetifier=true

# Kotlin code style
kotlin.code.style=official
